name: Test Action

on:
  repository_dispatch:
    types: [contentful.deploy]

jobs:
  use-action:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch data
      uses: ./
      with:
        file: 'testfile.json'
        url: 'https://cdn.contentful.com/spaces/oveaw8c9vpyp/environments/sandbox/content_types?access_token=v7FnV2SbIHbaJ212yc4qMnGW5oPfdyUpc1C9I_Sumc4'
      
    - name: list files
      run: ls

